# default PRO VARS (has to be  overwritten vi cli parameter)
PRO_DIR  ?= /tmp
PROJECT_NAME ?= pro

# REPO VARS
REPO_DIR  ?= .
STATIC_CONTENT_DEFAULT := README.md
BASE_CONFIG_NAME := .base
BASE_EXAMPLE_NAME := .example
BASE_CONFIG_DIR := $(REPO_DIR)$(XSLASH)$(BASE_CONFIG_NAME)
BASE_EXAMPLE_DIR := $(REPO_DIR)$(XSLASH)$(BASE_EXAMPLE_NAME)
BASE_CONFIG_ARCHIVE := $(REPO_DIR)$(XSLASH)$(BASE_CONFIG_NAME).tgz
EXAMPLE_ARCHIVE := $(REPO_DIR)$(XSLASH)$(BASE_EXAMPLE_NAME).tgz

# TARGETS FOR FOLDER CREATION INSIDE OF THE REPO 
# TO REFRESH THE ACHIVES FROM A PROJECT
CONFIG_DIR_S := $(BASE_CONFIG_DIR) $(BASE_EXAMPLE_DIR)
