# PROJECT VARS
BASE_DIR  := $(PROJECT_DIR)$(XSLASH)$(PROJECT_NAME)
STATIC_CONTENT_DEFAULT := README.md
MAKE_BASE_DIR := $(BASE_DIR)$(XSLASH)workspace
TEMPLATE_DIR := $(BASE_DIR)$(XSLASH)templates
LOCK_DIR := $(MAKE_BASE_DIR)$(XSLASH)loc
LOCK_DIR_INTERNAL := $(LOCK_DIR)$(XSLASH)internal
INSTALL_BASE := $(LOCK_DIR_INTERNAL)$(XSLASH)base-installed
STATIC_CONTENT_DIR := $(BASE_DIR)$(XSLASH)static
INSTALL_EXAMPLE := $(LOCK_DIR_INTERNAL)$(XSLASH)example-installed
PUBLIC_DIST_DIR := $(BASE_DIR)$(XSLASH)public
BUILD_DIR := $(BASE_DIR)$(XSLASH)build
PROJECT_CONFIG_FILE := $(BASE_DIR)$(XSLASH).common.mk 
# TAGETS FOR FOLDER  CREATION OF THE PROJECT
BASE_DIR_S := $(MAKE_BASE_DIR) $(LOCK_DIR) $(LOCK_DIR_INTERNAL) $(TEMPLATE_DIR) $(STATIC_CONTENT_DIR) $(PUBLIC_DIST_DIR) $(BUILD_DIR)
