include ../../.common.mk
MK_STEP                      := 0

STATIC_CONTENT_DOCUMENT_NAME ?= $(STATIC_CONTENT_DEFAULT)
STATIC_CONTENT_ORIGIN        := $(STATIC_CONTENT_DIR)
STATIC_CONTENT_DESTINATION   := $(BUILD_DIR)
#STATIC_CONTENT               := $(LOCK_DIR)$(XSLASH)$(STATIC_CONTENT_DOCUMENT_NAME)
STATIC_CONTENT               := $(STATIC_CONTENT_DESTINATION)$(XSLASH)$(MK_STEP).$(STATIC_CONTENT_DOCUMENT_NAME)

#.PHONY : $(STATIC_CONTENT)
$(STATIC_CONTENT) :
	$(ECHO) $(STATIC_CONTENT_DIR)
	$(CP--VERBOSE) $(STATIC_CONTENT_ORIGIN)$(XSLASH)$(STATIC_CONTENT_DOCUMENT_NAME) $(STATIC_CONTENT_DESTINATION)$(XSLASH)$(MK_STEP).$(STATIC_CONTENT_DOCUMENT_NAME)
	$(TOUCH) $(STATIC_CONTENT)

.PHONY : clean
clean : 
	$(RM-FV) $(STATIC_CONTENT)

.PHONY : all
all : 
	$(ECHO) $(STATIC_CONTENT) 


.DEFAULT_GOAL = $(STATIC_CONTENT)